/**
 * Deterministic, fictional extension state for product screenshots.
 *
 * This data is intentionally synthetic: it makes the UI look meaningfully used
 * without ever putting a developer's personal profile, resume, API key, or
 * application history into committed screenshots.
 */
export const DEMO_STATE = {
  settings: {
    privacy_consent: true,
    privacy_consent_at: '2026-01-15T12:00:00.000Z',
    gemini_model: 'auto',
    preferred_salary_min: 140000,
    preferred_salary_max: 220000,
    preferred_remote: true,
    work_authorization: 'US Citizen',
  },
  resume: {
    structured: {
      name: 'Jordan Morgan',
      email: 'jordan.morgan@example.test',
      phone: '(555) 010-0142',
      location: 'Arlington, VA',
      linkedin: 'https://www.linkedin.com/in/jordan-morgan-demo',
      github: 'https://github.com/jordan-morgan-demo',
      portfolio: 'https://jordan-morgan.example.test',
      current_company: 'Northstar Labs',
      current_title: 'Systems Engineer',
      summary: 'Systems engineer focused on cloud platforms, automation, reliability, and developer tooling.',
      years_of_experience: 10,
      skills: ['Cloud Infrastructure', 'Python', 'TypeScript', 'AWS', 'Kubernetes', 'Terraform'],
      experience: [
        {
          title: 'Systems Engineer',
          company: 'Northstar Labs',
          location: 'Arlington, VA',
          start_date: '2022-04',
          end_date: 'Present',
          bullets: [
            'Built cloud automation and internal developer tooling.',
            'Improved deployment reliability across distributed services.',
          ],
        },
        {
          title: 'Platform Engineer',
          company: 'Blue Harbor Software',
          location: 'Washington, DC',
          start_date: '2018-06',
          end_date: '2022-03',
          bullets: [
            'Automated infrastructure operations with Python and Terraform.',
            'Supported production Kubernetes workloads.',
          ],
        },
      ],
      education: [
        {
          degree: 'B.S. Computer Science',
          institution: 'Example State University',
          year: '2018',
        },
      ],
      certifications: ['AWS Certified Solutions Architect'],
      languages: ['English'],
    },
    excerpt: 'Jordan Morgan — Systems Engineer — Cloud infrastructure, automation, Python, TypeScript, AWS, Kubernetes, Terraform.',
    attachment: {
      name: 'jordan-morgan-resume.txt',
      mimeType: 'text/plain',
      source: 'upload',
      updatedAt: '2026-01-15T12:00:00.000Z',
      preview: 'Jordan Morgan — Systems Engineer — Cloud infrastructure, automation, Python, TypeScript, AWS, Kubernetes, Terraform.',
      downloadMode: 'text',
      data: '',
      text: 'Jordan Morgan\\nSystems Engineer\\nArlington, VA\\nCloud infrastructure, automation, Python, TypeScript, AWS, Kubernetes, Terraform.',
    },
  },
  applications: [
    {
      id: 'demo-app-001',
      company: 'Northstar Labs',
      title: 'Senior Systems Engineer',
      url: 'https://jobs.example.test/northstar/senior-systems-engineer',
      status: 'interview',
      sort_order: 4096,
      date: '2026-09-18',
      updated_at: '2026-09-20T14:00:00.000Z',
      source: 'greenhouse',
      first_response_at: '2026-09-20T14:00:00.000Z',
      jd_snippet: 'Own cloud infrastructure, developer tooling, and reliability initiatives across a growing platform.',
      description: 'Own cloud infrastructure, developer tooling, and reliability initiatives across a growing platform.',
      location: 'Remote · US',
      employment_type: 'Full-time',
      remote: true,
      pay_min: 165000,
      pay_max: 205000,
      salary_range: '$165,000 - $205,000',
      scorecard: 'Strong fit',
      verdict: 'Priority',
      answers_generated: true,
      fill_report: null,
    },
    {
      id: 'demo-app-002',
      company: 'Meridian Systems',
      title: 'Cloud Platform Engineer',
      url: 'https://jobs.example.test/meridian/cloud-platform-engineer',
      status: 'submitted',
      sort_order: 3072,
      date: '2026-09-16',
      updated_at: '2026-09-16T16:30:00.000Z',
      source: 'lever',
      first_response_at: '',
      jd_snippet: 'Build and operate secure cloud platforms used by engineering teams worldwide.',
      description: 'Build and operate secure cloud platforms used by engineering teams worldwide.',
      location: 'Washington, DC',
      employment_type: 'Full-time',
      remote: true,
      pay_min: 150000,
      pay_max: 190000,
      salary_range: '$150,000 - $190,000',
      scorecard: 'Good fit',
      verdict: 'Priority',
      answers_generated: true,
      fill_report: null,
    },
    {
      id: 'demo-app-003',
      company: 'Pine Ridge Analytics',
      title: 'DevOps Engineer',
      url: 'https://jobs.example.test/pine-ridge/devops-engineer',
      status: 'offer',
      sort_order: 2048,
      date: '2026-09-09',
      updated_at: '2026-09-19T13:15:00.000Z',
      source: 'ashby',
      first_response_at: '2026-09-15T15:30:00.000Z',
      jd_snippet: 'Help scale CI/CD, observability, and infrastructure automation for a data platform.',
      description: 'Help scale CI/CD, observability, and infrastructure automation for a data platform.',
      location: 'Remote · US',
      employment_type: 'Full-time',
      remote: true,
      pay_min: 155000,
      pay_max: 195000,
      salary_range: '$155,000 - $195,000',
      scorecard: 'Excellent fit',
      verdict: 'Top match',
      answers_generated: true,
      fill_report: null,
    },
    {
      id: 'demo-app-004',
      company: 'Atlas Health Tech',
      title: 'Platform Reliability Engineer',
      url: 'https://jobs.example.test/atlas/platform-reliability-engineer',
      status: 'submitted',
      sort_order: 1024,
      date: '2026-09-04',
      updated_at: '2026-09-04T11:00:00.000Z',
      source: 'remotive',
      first_response_at: '',
      jd_snippet: 'Improve platform reliability and developer experience across healthcare workloads.',
      description: 'Improve platform reliability and developer experience across healthcare workloads.',
      location: 'Remote · US',
      employment_type: 'Full-time',
      remote: true,
      pay_min: 145000,
      pay_max: 180000,
      salary_range: '$145,000 - $180,000',
      scorecard: 'Good fit',
      verdict: 'Follow up',
      answers_generated: true,
      fill_report: null,
    },
  ],
  learnedDefaults: {
    'Are you authorized to work in the United States?': 'Yes',
    'Are you willing to work remotely?': 'Yes',
    'What is your preferred salary range?': '$160,000 - $200,000',
    'When can you start?': 'Two weeks after accepting an offer',
  },
  ignoredLearnedDefaults: {},
  lastAnswers: {
    'Why are you interested in this role?': 'The role combines cloud reliability, automation, and developer tooling with a product-focused engineering team.',
    'Describe your experience with infrastructure automation.': 'I have built repeatable infrastructure and deployment automation using Python, Terraform, and cloud-native tooling.',
  },
  lastTrackedApplicationId: 'demo-app-001',
};

export async function seedDemoState(page) {
  await page.evaluate(async (state) => {
    await chrome.storage.local.clear();
    await chrome.storage.local.set(state);
  }, DEMO_STATE);
}
