# docker-compose.yml

services:
  test:
    image: ats-fill-test
    build:
      context: ..
      target: test
    command: npm test

  lint:
    image: ats-fill-lint
    build:
      context: ..
      target: test
    command: npm run lint

  coverage:
    image: ats-fill-coverage
    build:
      context: ..
      target: test
    command: npm run test:coverage

  e2e:
    image: ats-fill-e2e
    build:
      context: ..
      target: e2e
    command: npm run test:e2e
